### ISSUE TITLE
Running the container locally gives a faulty Layout

### ISSUE THREAD

**Issue by Kirk1984** [PussTheCat-org/docker-libremdb-quay#2]
![Screenshot 2022-08-19 at 21-30-58 About libremdb](https://user-images.githubusercontent.com/29674972/185694671-1275e6fe-2259-4c0e-a676-40b529d1418f.png)

When i try to run the Container locally (http://IP:3000) the Website looks like in the screenshot.

A Manual non-docker install under my Fedora Workstation looks normal (http://localhost:3000).

**Comment by TheFrenchGhosty** [comment]
Won't be a problem after #3
